columns_mapper = {"Sales": "Revenue",
                  "SalesGrowth%": "PercentRevenueGrowth",
                  "RevenueGrowth%": "PercentRevenueGrowth",
                  "FinancingProfit": "OperatingProfit",
                  "FPM%": "PercentOPM",
                  "OPM%": "PercentOPM",
                  "MaterialCost%": "PercentMaterialCost",
                  "ManufacturingCost%": "PrecentManufacturingCost",
                  "EmployeeCost%": "PrecentEmployeeCost",
                  "OtherCost%": "PrecentOtherCost",
                  "Tax%": "PrecentTax",
                  "DividendPayout%": "PercentDividendPayout",
                  "ROCE%": "PercentROCE",
                  "ROE%": "PercentROE",
                  "NetProfit": "PAT",
                  "CashfromFinancingActivity": "CashFromFinancingActivity",
                  "CashfromInvestingActivity": "CashFromInvestingActivity",
                  "CashfromOperatingActivity": "CashFromOperatingActivity",
                  "Directtaxes": "DirectTaxes",
                  "Dividendsreceived": "DividendReceived",
                  "Dividendspaid": "DividendsPaid",
                  "Financialliabilities": "FinancialLiabilities",
                  "Fixedassetspurchased": "FixedAssetsPurchased",
                  "Fixedassetssold": "FixedAssetsSold",
                  "Interestpaidfin": "InterestPaidFin",
                  "Interestreceived": "InterestReceived",
                  "Investmentincome": "InvestmentIncome",
                  "Investmentingroupcos": "InvestmentInGroupCos",
                  "Investmentspurchased": "InvestmentsPurchased",
                  "Investmentssold": "InvestmentsSold",
                  "Noncontrollingint": "NonControllingInt",
                  "Operatinginvestments": " OperatingInvestments",
                  "Otherassetitems": "OtherAssetItems",
                  "Otherfinancingitems": " OtherFinancingItems",
                  "Otherinvestingitems": "OtherInvestingItems",
                  "Otherliabilityitems": "OtherLiabilityItems",
                  "Proceedsfromshares": "ProceedsFromShares",
                  "Proceedsfromdebentures": "ProceedsFromDebentures",
                  "Proceedsfromborrowings": "ProceedsFromBorrowings",
                  "Profitbeforetax": "ProfitBeforeTax",
                  "Profitfromoperations": "ProfitFromOperations",
                  "Redemptionofdebentures": "RedemptionOfDebentures",
                  "Repaymentofborrowings": "RepaymentOfBorrowings",
                  "Sharesacqcancelled": "SharesAcqCancelled",
                  "Tradereceivables": "TradeReceivables",
                  "Workingcapitalchanges": "WorkingCapitalChanges"
                  }

defaults = {
    'Long-term debt': 0,
    'Current debt': 0,
    'Depreciation & amortisation': 0,
    'Income tax expense': 0,
    'Total non-current assets': 0,
    'Total current assets': 0,
    'Total assets': 0,
    'Total cash': 0,
    'Total current liabilities': 0,
    'Net income': 0,
    "Total stockholders' equity": 0,
    'Total revenue': 0,
    'Inventory': 0,
    'Interest expense': 0,
    'Net receivables': 0,
    'Accounts payable': 0,
    'Cost of revenue': 0,
    'Net cash provided by operating activities': 0,
    'Diluted average shares': 0,
    'Retained earnings': 0
}
